import type { HomeProject } from './types/projects';

const homeProjects: HomeProject[] = [
  {
    id: 13,
    title: 'Averys',
    year: '2026',
    order: 202603,
    placeholder: '/assets/media/projects/web-dev/averys/averys2-960.png',
    introPlaceholder: '/assets/media/projects/web-dev/averys/averyslogomedia-960.png',
    introDurationMs: 3000,
    src: '/media/videos/averys-video1.mp4',
    projectLink: '/achievements/web-developement/averys',
  },
  {
    id: 11,
    title: 'Private event ops dashboard',
    year: '2026',
    order: 202602,
    placeholder:
      '/assets/media/projects/web-dev/private-events-dashboard/private-events-dashboard-960.png',
    src: '/media/videos/private-events-dashboard-1.mp4',
    srcAlt: '/media/videos/private-events-dashboard-2.mp4',
    projectLink:
      '/achievements/web-developement/private-event-operations-dashboard-wedding-edition',
  },
  {
    id: 10,
    title: 'Mark Conlan',
    year: '2026',
    order: 202601,
    placeholder: '/assets/media/common/images/web-dev/mark-conlan/mark-conlan-temp-960.avif',
    src: '/media/videos/mark-conlan-home-web.mp4',
    projectLink: '/achievements/web-developement/mark-conlan',
  },
  {
    id: 12,
    title: 'Baud Architectes',
    year: '2026',
    order: 202600,
    placeholder: '/assets/media/projects/branding/baud/Group%2021-960.png',
    projectLink: '/achievements/branding/baud',
  },
  {
    id: 14,
    title: 'Trio Linaris',
    year: '2026',
    order: 202604,
    placeholder: '/assets/media/projects/branding/tio-linaris/tio-linaris-cover-960.png',
    projectLink: '/achievements/branding/trio-linaris',
  },
  {
    id: 9,
    title: 'Flou',
    year: '2025',
    order: 202511,
    placeholder: '/assets/media/branding/flou/flou-home-960.png',
    projectLink: '/achievements/branding/flou',
  },
  {
    id: 8,
    title: 'Can Pruna',
    year: '2025',
    order: 202510,
    placeholder: '/assets/media/common/images/web-dev/canpruna/canpruna-temp-960.avif',
    src: '/media/videos/canpruna-accueil.mp4',
    projectLink: '/achievements/web-developement/canpruna-accomodation',
  },
  {
    id: 7,
    title: 'C & N wedding',
    year: '2025',
    order: 202508,
    placeholder: '/assets/media/common/images/web-dev/boda-carmen-nestor/C&N-temp-960.avif',
    src: '/media/videos/c-and-n-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-carmen-nestor',
  },
  {
    id: 6,
    title: 'L & P wedding',
    year: '2025',
    order: 202507,
    placeholder: '/assets/media/common/images/web-dev/boda-lis-pavlos/L&P-temp-960.avif',
    src: '/media/videos/l-and-p-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-lis-pavlos',
  },
  {
    id: 5,
    title: 'Bellelachaise',
    year: '2025',
    order: 202505,
    placeholder: '/assets/media/common/images/web-dev/bellelachaise/blc-temp-960.avif',
    src: '/media/videos/blc-accueil.mp4',
    projectLink: '/achievements/web-developement/bellelachaise',
  },
  {
    id: 4,
    title: 'Louis Cattiaux',
    year: '2025',
    order: 202502,
    placeholder: '/assets/media/common/images/web-dev/louis-cattiaux/lc-temp-960.avif',
    src: '/media/videos/lc-accueil.mp4',
    projectLink: '/achievements/web-developement/louis-cattiaux',
  },

];

export default homeProjects;
