import type { HomeProject } from './types/projects';

const homeProjects: HomeProject[] = [
  {
    id: 11,
    title: 'Private event ops dashboard',
    year: '2026',
    placeholder: '/assets/media/projects/web-dev/liana/admin-rsvp.png',
    src: '/media/videos/private-events-dashboard-1.mp4',
    srcAlt: '/media/videos/private-events-dashboard-2.mp4',
    projectLink: '/achievements/web-developement/private-event-operations-dashboard-wedding-edition',
  },
  {
    id: 10,
    title: 'Mark Conlan',
    year: '2026',
    placeholder: '/assets/media/common/legacy-img/web-dev/mark-conlan/mark-conlan-temp-960.avif',
    src: '/media/videos/mark-conlan-home-web.mp4',
    projectLink: '/achievements/web-developement/mark-conlan',
  },
  {
    id: 9,
    title: 'Flou',
    year: '2025',
    placeholder: '/assets/media/branding/flou/flou-home-960.png',
    projectLink: '/achievements/branding/flou',
  },
  {
    id: 8,
    title: 'Can Pruna',
    year: '2025',
    placeholder: '/assets/media/common/legacy-img/web-dev/canpruna/canpruna-temp-960.avif',
    src: '/media/videos/canpruna-accueil.mp4',
    projectLink: '/achievements/web-developement/canpruna-accomodation',
  },
  {
    id: 7,
    title: 'C & N wedding',
    year: '2025',
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-carmen-nestor/C&N-temp-960.avif',
    src: '/media/videos/C&N-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-carmen-nestor',
  },
  {
    id: 6,
    title: 'L & P wedding',
    year: '2025',
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-lis-pavlos/L&P-temp-960.avif',
    src: '/media/videos/L&P-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-lis-pavlos',
  },
  {
    id: 5,
    title: 'Bellelachaise',
    year: '2025',
    placeholder: '/assets/media/common/legacy-img/web-dev/bellelachaise/blc-temp-960.avif',
    src: '/media/videos/blc-accueil.mp4',
    projectLink: '/achievements/web-developement/bellelachaise',
  },
  {
    id: 4,
    title: 'Louis Cattiaux',
    year: '2025',
    placeholder: '/assets/media/common/legacy-img/web-dev/louis-cattiaux/lc-temp-960.avif',
    src: '/media/videos/lc-accueil.mp4',
    projectLink: '/achievements/web-developement/louis-cattiaux',
  },

  {
    id: 3,
    title: 'N & M wedding',
    year: '2024',
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-natalia-mauricio/N&M-accueil-960.avif',
    src: '/media/videos/N&M-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-natalia-y-mauricio',
  },
  {
    id: 2,
    title: 'Tranche de cake',
    year: '2024',
    placeholder: '/assets/media/common/legacy-img/web-dev/tranche-de-cake/tranchedecake-960.avif',
    src: '/media/videos/video-tdc-accueil.mp4',
    projectLink: '/achievements/web-developement/tranche-de-cake',
  },
  {
    id: 1,
    title: 'M & P wedding',
    year: '2024',
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-marta-pedro/M&P-temp-960.avif',
    src: '/media/videos/M&P-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-marta-y-pedro',
  },
];

export default homeProjects;
