export default [
  {
    id: 14,
    title: "Can Pruna accomodation",
    year: "2025",
    placeholder: require("./assets/img/canpruna-temp.png"),
    src: require("../public/media/videos/canpruna-accueil.mp4"),
    projectLink: "/achievements/web-developement/canpruna-accomodation",
  },
  {
    id: 13,
    title: "",
    year: "",
    placeholder: require("./assets/img/illustration1-0.png"),
    src: require("../public/media/videos/Google_Mio_Color_1080x1080.mp4"),
    projectLink: "",
  },
  {
    id: 12,
    title: "Carmen & Nestor wedding",
    year: "2025",
    placeholder: require("./assets/img/C&N-temp.png"),
    src: require("../public/media/videos/C&N1-accueil.mp4"),
    projectLink: "/achievements/web-developement/boda-carmen-nestor",
  },
  {
    id: 11,
    title: "",
    year: "",
    placeholder: require("./assets/img/illustration2-0.png"),
    src: require("../public/media/videos/Google_Mio_Elevation_1080x1080.mp4"),
    projectLink: "",
  },
  {
    id: 10,
    title: "Lis & Pavlos wedding",
    year: "2025",
    placeholder: require("./assets/img/L&P-temp.png"),
    src: require("../public/media/videos/L&P-accueil.mp4"),
    projectLink: "/achievements/web-developement/boda-lis-pavlos",
  },
  {
    id: 9,
    title: "Bellelachaise",
    year: "2025",
    placeholder: require("./assets/img/blc-temp.png"),
    src: require("../public/media/videos/blc-accueil.mp4"),
    projectLink: "/achievements/web-developement/bellelachaise",
  },
  {
    id: 8,
    title: "Louis Cattiaux archives",
    year: "2025",
    placeholder: require("./assets/img/lc-temp.png"),
    src: require("../public/media/videos/lc-accueil.mp4"),
    projectLink: "/achievements/web-developement/louis-cattiaux",
  },
  {
    id: 7,
    title: "Boda Natalia & Mauricio",
    year: "2024",
    placeholder: require("./assets/img/N&M-accueil.png"),
    src: require("../public/media/videos/N&M-accueil.mp4"),
    projectLink: "/achievements/web-developement/boda-natalia-y-mauricio",
  },
  {
    id: 6,
    title: "",
    year: "",
    placeholder: require("./assets/img/illustration3-0.png"),
    src: require("../public/media/videos/Google_Mio_Web_1080x1080.mp4"),
    projectLink: "",
  },
  {
    id: 5,
    title: "Tranche de cake",
    year: "2024",
    placeholder: require("./assets/img/tranchedecake.png"),
    src: require("../public/media/videos/video-tdc-accueil.mp4"),
    projectLink: "/achievements/web-developement/tranche-de-cake",
  },
  {
    id: 4,
    title: "",
    year: "",
    placeholder: require("./assets/img/illustration4-0.png"),
    src: require("../public/media/videos/Google_Mio_Shape_1080x1080.mp4"),
    projectLink: "",
  },
  {
    id: 3,
    title: "Boda Marta & Pedro",
    year: "2024",
    placeholder: require("./assets/img/M&P-temp.png"),
    src: require("../public/media/videos/M&P-accueil.mp4"),
    projectLink: "/achievements/web-developement/boda-marta-y-pedro",
  },
  {
    id: 2,
    title: "Académie Clé Do Ré",
    year: "2024",
    placeholder: require("./assets/img/cledore-temp.png"),
    src: require("../public/media/videos/video-cledore-accueil.mp4"),
    projectLink: "/achievements/web-developement/academie-cle-do-re",
  },
  {
    id: 1,
    title: "",
    year: "",
    placeholder: require("./assets/img/illustration5-0.png"),
    src: require("../public/media/videos/Google_Mio_UnderstandingLayout_1080x1080.mp4"),
    projectLink: "",
  },
];
