import type { WebDevProject } from './types/projects';

declare const require: (path: string) => string;

const webDevProjects: WebDevProject[] = [
  {
    id: 14,
    title: 'Mark Conlan',
    year: '2026',
    order: 202601,
    placeholder: '/assets/media/common/legacy-img/web-dev/mark-conlan/mark-conlan-temp-960.png',
    src: '/media/videos/mark-conlan-2-web.mp4',
    projectLink: '/achievements/web-developement/mark-conlan',
  },
  {
    id: 13,
    title: 'Can Pruna',
    year: '2025',
    order: 202510,
    placeholder: '/assets/media/common/legacy-img/web-dev/canpruna/canpruna-temp-960.png',
    src: require('../public/media/videos/canpruna-accueil.mp4'),
    projectLink: '/achievements/web-developement/canpruna-accomodation',
  },
  {
    id: 12,
    title: 'C & N wedding',
    year: '2025',
    order: 202508,
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-carmen-nestor/C&N-temp-960.png',
    src: require('../public/media/videos/C&N-accueil.mp4'),
    projectLink: '/achievements/web-developement/boda-carmen-nestor',
  },
  {
    id: 11,
    title: 'L & P wedding',
    year: '2025',
    order: 202507,
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-lis-pavlos/L&P-temp-960.png',
    src: require('../public/media/videos/L&P-accueil.mp4'),
    projectLink: '/achievements/web-developement/boda-lis-pavlos',
  },
  {
    id: 10,
    title: 'Bellelachaise',
    year: '2025',
    order: 202505,
    placeholder: '/assets/media/common/legacy-img/web-dev/bellelachaise/blc-temp-960.png',
    src: require('../public/media/videos/blc-accueil.mp4'),
    projectLink: '/achievements/web-developement/bellelachaise',
  },
  {
    id: 9,
    title: 'Louis Cattiaux archives',
    year: '2025',
    order: 202502,
    placeholder: '/assets/media/common/legacy-img/web-dev/louis-cattiaux/lc-temp-960.png',
    src: require('../public/media/videos/lc-accueil.mp4'),
    projectLink: '/achievements/web-developement/louis-cattiaux',
  },
  {
    id: 8,
    title: 'N & M wedding',
    year: '2024',
    order: 202411,
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-natalia-mauricio/N&M-accueil-960.png',
    src: require('../public/media/videos/N&M-accueil.mp4'),
    projectLink: '/achievements/web-developement/boda-natalia-y-mauricio',
  },
  {
    id: 7,
    title: 'Tranche de cake',
    year: '2024',
    order: 202408,
    placeholder: '/assets/media/common/legacy-img/web-dev/tranche-de-cake/tranchedecake-960.png',
    src: require('../public/media/videos/video-tdc-accueil.mp4'),
    projectLink: '/achievements/web-developement/tranche-de-cake',
  },
  {
    id: 6,
    title: 'M & P wedding',
    year: '2024',
    order: 202407,
    placeholder: '/assets/media/common/legacy-img/web-dev/boda-marta-pedro/M&P-temp-960.png',
    src: require('../public/media/videos/M&P-accueil.mp4'),
    projectLink: '/achievements/web-developement/boda-marta-y-pedro',
  },
  {
    id: 5,
    title: 'Académie Clé Do Ré',
    year: '2024',
    order: 202406,
    placeholder: '/assets/media/common/legacy-img/web-dev/academie-cledore/cledore-temp-960.png',
    src: require('../public/media/videos/video-cledore-accueil.mp4'),
    projectLink: '/achievements/web-developement/academie-cle-do-re',
  },
  {
    id: 4,
    title: 'La petite serre urbaine',
    year: '2024',
    order: 202405,
    placeholder: '/assets/media/common/legacy-img/web-dev/la-petite-serre-urbaine/la-petite-serre-urbaine-temp-960.png',
    src: require('../public/media/videos/video-petite-serre.mp4'),
    projectLink: '/achievements/web-developement/la-petite-serre-urbaine',
  },
  {
    id: 3,
    title: 'The Perfect Hamburger',
    order: 202404,
    year: '2024',
    placeholder: '/assets/media/common/legacy-img/web-dev/hamburger/hamburger-temp-960.png',
    src: require('../public/media/videos/video-the-perfect-burger-accueil.mp4'),
    projectLink: '/achievements/web-developement/the-perfect-hamburger',
  },
  {
    id: 2,
    title: 'Didacmanía',
    order: 202403,
    year: '2024',
    placeholder: '/assets/media/common/legacy-img/web-dev/didacmania/didacmania-temp-960.png',
    src: require('../public/media/videos/video-didacmania-accueil.mp4'),
    projectLink: '/achievements/web-developement/didacmania',
  },
  {
    id: 1,
    title: 'Creyda Yoga',
    order: 202312,
    year: '2023',
    placeholder: '/assets/media/common/legacy-img/web-dev/creyda/creyda-temp-960.png',
    src: require('../public/media/videos/video-creyda-short-accueil.mp4'),
    projectLink: '/achievements/web-developement/creyda',
  },
];

export default webDevProjects;
