import type { WebDevProject } from './types/projects';

const webDevProjects: WebDevProject[] = [
  {
    id: 17,
    title: 'Alyssa Coleman - Back of House',
    year: '2026',
    order: 202605,
    placeholder:
      '/assets/media/projects/web-dev/alyssa-coleman-back-of-house/alyssa-coleman-back-of-house-home-poster.webp',
    src: '/media/videos/alyssa-coleman-back-of-house-home.mp4',
    projectLink: '/achievements/web-developement/alyssa-coleman-back-of-house',
  },
  {
    id: 16,
    title: 'Averys',
    year: '2026',
    order: 202603,
    placeholder: '/assets/media/projects/web-dev/averys/averys2-960.png',
    introPlaceholder: '/assets/media/projects/web-dev/averys/averyslogomedia-960.png',
    introDurationMs: 3000,
    src: '/media/videos/averys-video1.mp4',
    projectLink: '/achievements/web-developement/averys',
  },
  {
    id: 15,
    title: 'Private event operations dashboard (Wedding Edition)',
    year: '2026',
    order: 202602,
    placeholder:
      '/assets/media/projects/web-dev/private-events-dashboard/private-events-dashboard-960.png',
    src: '/media/videos/private-events-dashboard-1.mp4',
    srcAlt: '/media/videos/private-events-dashboard-2.mp4',
    projectLink:
      '/achievements/web-developement/private-event-operations-dashboard-wedding-edition',
  },
  {
    id: 14,
    title: 'Mark Conlan',
    year: '2026',
    order: 202601,
    placeholder: '/assets/media/common/images/web-dev/mark-conlan/mark-conlan-temp-960.avif',
    src: '/media/videos/mark-conlan-2-web.mp4',
    projectLink: '/achievements/web-developement/mark-conlan',
  },
  {
    id: 13,
    title: 'Can Pruna',
    year: '2025',
    order: 202510,
    placeholder: '/assets/media/common/images/web-dev/canpruna/canpruna-temp-960.avif',
    src: '/media/videos/canpruna-accueil.mp4',
    projectLink: '/achievements/web-developement/canpruna-accomodation',
  },
  {
    id: 12,
    title: 'C & N wedding',
    year: '2025',
    order: 202508,
    placeholder: '/assets/media/common/images/web-dev/boda-carmen-nestor/C&N-temp-960.avif',
    src: '/media/videos/c-and-n-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-carmen-nestor',
  },
  {
    id: 11,
    title: 'L & P wedding',
    year: '2025',
    order: 202507,
    placeholder: '/assets/media/common/images/web-dev/boda-lis-pavlos/L&P-temp-960.avif',
    src: '/media/videos/l-and-p-accueil.mp4',
    projectLink: '/achievements/web-developement/boda-lis-pavlos',
  },
  {
    id: 10,
    title: 'Bellelachaise',
    year: '2025',
    order: 202505,
    placeholder: '/assets/media/common/images/web-dev/bellelachaise/blc-temp-960.avif',
    src: '/media/videos/blc-accueil.mp4',
    projectLink: '/achievements/web-developement/bellelachaise',
  },
  {
    id: 9,
    title: 'Louis Cattiaux archives',
    year: '2025',
    order: 202502,
    placeholder: '/assets/media/common/images/web-dev/louis-cattiaux/lc-temp-960.avif',
    src: '/media/videos/lc-accueil.mp4',
    projectLink: '/achievements/web-developement/louis-cattiaux',
  },
  {
    id: 8,
    title: 'Tranche de cake',
    year: '2024',
    order: 202408,
    placeholder: '/assets/media/common/images/web-dev/tranche-de-cake/tranchedecake-960.avif',
    src: '/media/videos/video-tdc-accueil.mp4',
    projectLink: '/achievements/web-developement/tranche-de-cake',
  },
  {
    id: 6,
    title: 'M & P wedding',
    year: '2024',
    order: 202407,
    placeholder: '/assets/media/projects/web-dev/boda-marta-y-pedro/boda-marta-y-pedro-home-960.avif',
    src: '/media/videos/boda-marta-y-pedro-scroll-3.mp4',
    projectLink: '/achievements/web-developement/boda-marta-y-pedro',
  },
  {
    id: 5,
    title: 'Académie Clé Do Ré',
    year: '2024',
    order: 202406,
    placeholder: '/assets/media/projects/web-dev/academie-cle-do-re/academie-cle-do-re-hero-960.avif',
    src: '/media/videos/academie-cle-do-re-scroll-1.mp4',
    projectLink: '/achievements/web-developement/academie-cle-do-re',
  },
  {
    id: 4,
    title: 'La petite serre urbaine',
    year: '2024',
    order: 202405,
    placeholder:
      '/assets/media/projects/web-dev/la-petite-serre-urbaine/la-petite-serre-urbaine-home-1-960.avif',
    src: '/media/videos/video-petite-serre.mp4',
    projectLink: '/achievements/web-developement/la-petite-serre-urbaine',
  },
  {
    id: 3,
    title: 'The Perfect Hamburger',
    order: 202404,
    year: '2024',
    placeholder: '/assets/media/projects/web-dev/hamburger/hamburger-intro-960.avif',
    src: '/media/videos/video-the-perfect-burger-accueil.mp4',
    projectLink: '/achievements/web-developement/the-perfect-hamburger',
  },
  {
    id: 2,
    title: 'Didacmanía',
    order: 202403,
    year: '2024',
    placeholder: '/assets/media/common/images/web-dev/didacmania/didacmania-temp-960.avif',
    src: '/media/videos/video-didacmania-accueil.mp4',
    projectLink: '/achievements/web-developement/didacmania',
  },
  {
    id: 1,
    title: 'Creyda Yoga',
    order: 202312,
    year: '2023',
    placeholder: '/assets/media/common/images/web-dev/creyda/creyda-temp-960.avif',
    src: '/media/videos/video-creyda-short-accueil.mp4',
    projectLink: '/achievements/web-developement/creyda',
  },
];

export default webDevProjects;
